#!/bin/sh
#/home/ec2-user/apache-tomcat-8.0.35/bin/catalina.sh stop
cd /home/ec2-user/apache-tomcat-8.0.35/webapps
rm -rf helloWorld-0.1-dev.war
sleep 10
cp -rf /home/ec2-user/.jenkins/jobs/Hello_World/workspace/dist/helloWorld-0.1-dev.war .
#/home/ec2-user/apache-tomcat-8.0.35/bin/catalina.sh start
